# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import trade_data_pb2 as trade__data__pb2
import trade_service_pb2 as trade__service__pb2


class TradeStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.orderNewSingle = channel.unary_unary(
        '/balance.Trade/orderNewSingle',
        request_serializer=trade__service__pb2.OrderNewSingleRequest.SerializeToString,
        response_deserializer=trade__data__pb2.Order.FromString,
        )
    self.orderAmendSingle = channel.unary_unary(
        '/balance.Trade/orderAmendSingle',
        request_serializer=trade__service__pb2.OrderAmendSingleRequest.SerializeToString,
        response_deserializer=trade__data__pb2.Order.FromString,
        )
    self.orderCancelSingle = channel.unary_unary(
        '/balance.Trade/orderCancelSingle',
        request_serializer=trade__service__pb2.OrderCancelSingleRequest.SerializeToString,
        response_deserializer=trade__data__pb2.Order.FromString,
        )
    self.accountAsset = channel.unary_unary(
        '/balance.Trade/accountAsset',
        request_serializer=trade__service__pb2.AccountAssetRequest.SerializeToString,
        response_deserializer=trade__data__pb2.AccountAsset.FromString,
        )
    self.accountOrderList = channel.unary_unary(
        '/balance.Trade/accountOrderList',
        request_serializer=trade__service__pb2.AccountOrderListRequest.SerializeToString,
        response_deserializer=trade__data__pb2.AccountOrderList.FromString,
        )


class TradeServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def orderNewSingle(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def orderAmendSingle(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def orderCancelSingle(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def accountAsset(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def accountOrderList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TradeServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'orderNewSingle': grpc.unary_unary_rpc_method_handler(
          servicer.orderNewSingle,
          request_deserializer=trade__service__pb2.OrderNewSingleRequest.FromString,
          response_serializer=trade__data__pb2.Order.SerializeToString,
      ),
      'orderAmendSingle': grpc.unary_unary_rpc_method_handler(
          servicer.orderAmendSingle,
          request_deserializer=trade__service__pb2.OrderAmendSingleRequest.FromString,
          response_serializer=trade__data__pb2.Order.SerializeToString,
      ),
      'orderCancelSingle': grpc.unary_unary_rpc_method_handler(
          servicer.orderCancelSingle,
          request_deserializer=trade__service__pb2.OrderCancelSingleRequest.FromString,
          response_serializer=trade__data__pb2.Order.SerializeToString,
      ),
      'accountAsset': grpc.unary_unary_rpc_method_handler(
          servicer.accountAsset,
          request_deserializer=trade__service__pb2.AccountAssetRequest.FromString,
          response_serializer=trade__data__pb2.AccountAsset.SerializeToString,
      ),
      'accountOrderList': grpc.unary_unary_rpc_method_handler(
          servicer.accountOrderList,
          request_deserializer=trade__service__pb2.AccountOrderListRequest.FromString,
          response_serializer=trade__data__pb2.AccountOrderList.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'balance.Trade', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
